version: '3'
services:
  mymongodb:
    build: 
      dockerfile: Dockerfile
      context: ./mongodb
    # เปลี่ยนจาก image: mymongodb:1.0 มาเป็น build ผ่าน Dockerfile
    restart: always
    networks:
      - shoppers
  mynodejsapp:
    depends_on:
      - mymongodb
    build: 
      dockerfile: Dockerfile
      context: ./nodejs
    restart: always
    volumes:
      - /usr/app/node_modules
      - /Users/topteranai/docker-bootcamp/c2react-nodejs-mongodb/nodejs:/usr/app
    networks:
      - shoppers
    ports:
      - 8000:8000
    environment:
      DATABASE_USER: admin
      DATABASE_PASSWORD: 1111
      DATABASE_HOST: mymongodb
  # myreactapp: [nginx]
  #   depends_on:
  #     - mymongodb
  #     - mynodejsapp
  #   build: 
  #     dockerfile: Dockerfile.prod
  #     context: ./frontend
  #   ports:
  #     - 3000:80
  #   # Dockerfile.prod nginx expose port 80
  #   restart: always
  #   networks:
  #     - shoppers
  myreactapp:
    depends_on:
      - mymongodb
      - mynodejsapp
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - /usr/app/node_modules
      - /Users/topteranai/docker-bootcamp/c2react-nodejs-mongodb/frontend:/usr/app
    restart: always
    networks:
      - shoppers
    
networks:
  shoppers: