version: '3'

services:
  db:
    image: mysql:5.7
    networks:
      - wordpress
    # docker run --network wordpress
    volumes:
      - db_data:/var/lib/mysql
    # docker run -v db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
    # docker run -e MYSQL_ROOT_PASSWORD=1111
  wordpress:
    depends_on:
      - db
    # คำสั่งให้ทำงานหลักจาก db ทำงานแล้ว
    image: wordpress
    networks:
      - wordpress
    ports:
      - 888:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1111
  phpmyadmin:
    depends_on:
        - db
      # คำสั่งให้ทำงานหลักจาก db ทำงานแล้ว
    image: phpmyadmin
    networks:
      - wordpress
    restart: always
    # เมื่อมีปัญหา หรือ error จะให้ restart ตลอดเวลา
    ports:
      - 8888:80

volumes:
  db_data:

networks:
  wordpress: