FROM node:alpine as builder
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY ./ ./
RUN npm run build
# ทำการสร้าง file เป็น static
CMD ["npm", "run", "start"]

FROM nginx
EXPOSE 80
COPY --from=builder /usr/app/build /usr/share/nginx/html
# from=builder = builder ตัวบน
# copy builder ที่ path /usr/app/build
# copy ไปที่ nginx ที่ path /usr/share/nginx/html

